apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: agogos
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: agogos-ca
      containers:
      - name: graphql-gateway
        image: soluto/agogos-graphql-gateway
        env:
          - name: REGISTRY_URL
            value: 'registry:81'
          - name: LOG_LEVEL
            value: DEBUG
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            path: /health
            port: 8011
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /graphql
            port: 8011
          initialDelaySeconds: 3
          periodSeconds: 3
      - name: airbag
        image: alex4soluto/airbag
        volumeMounts:
          - name: gateway-configmap
            mountPath: /app/data/airbag-config.json
            subPath: airbag-config.json
            readOnly: true
      volumes:
        - name: gateway-configmap
          configMap:
            name: gateway-configmap
---
kind: Service
apiVersion: v1
metadata:
  namespace: agogos
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configmap
  namespace: agogos
data:
  airbag-config.json: |
        {
          "backend": "http://localhost:8011",
          "JWTProviders": [
              {
                  "iss": "http://oidc-server-mock.oidc-namespace",
                  "aud": "agogos-scope"
              }
            ],
            "UnauthenticatedPaths": [
                "/health",
                "/metrics"
            ]
        }
---