apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: agogos
  name: registry
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      serviceAccountName: agogos-ca
      containers:
      - name: registry
        image: soluto/agogos-registry
        env:
          - name: PORT
            value: "80"
          - name: GRPC_PORT
            value: "81"
          - name: REMOTESOURCE__KUBERNETES
            value: http://gql-controller
          - name: NODE_ENV
            value: development
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  namespace: agogos
  name: registry
spec:
  selector:
    app: registry
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: grpc
      port: 81
      targetPort: 81
