apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: gql-controller
webhooks:
  - name: schema-validation-webhook.agogos.platform
    rules:
      - apiGroups:
          - agogos.app
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - schemas
          - upstreams
          - upstreamclientcredentials
        scope: "Namespaced"
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: "agogos"
        name: "gql-controller"
        path: "/validate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZpRENDQTNBQ0NRQ3dzaGcwZHRzQW9UQU5CZ2txaGtpRzl3MEJBUXNGQURDQmhURUxNQWtHQTFVRUJoTUMKU1V3eEREQUtCZ05WQkFnTUExUk1WakVSTUE4R0ExVUVCd3dJVkdWc0lFRjJhWFl4RHpBTkJnTlZCQW9NQmxOdgpiSFYwYnpFaU1DQUdBMVVFQXd3WlozRnNMV052Ym5SeWIyeHNaWEl1WVdkdloyOXpMbk4yWXpFZ01CNEdDU3FHClNJYjNEUUVKQVJZUllXZHZaMjl6UUhOdmJIVjBieTVqYjIwd0hoY05NVGt3TnpJNE1UTXhNREV5V2hjTk1Ua3cKT0RJM01UTXhNREV5V2pDQmhURUxNQWtHQTFVRUJoTUNTVXd4RERBS0JnTlZCQWdNQTFSTVZqRVJNQThHQTFVRQpCd3dJVkdWc0lFRjJhWFl4RHpBTkJnTlZCQW9NQmxOdmJIVjBiekVpTUNBR0ExVUVBd3daWjNGc0xXTnZiblJ5CmIyeHNaWEl1WVdkdloyOXpMbk4yWXpFZ01CNEdDU3FHU0liM0RRRUpBUllSWVdkdloyOXpRSE52YkhWMGJ5NWoKYjIwd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUUN2N0xhTWsvQjVKWjlBaW8zdgorbzZmWUtlbzAxTExFbUxpdWE4L21GczdhREwxcXZLWmJ6eXBxMmJPOGQ1ZGZzUE1tYW9QNE1HZHpwbTB4KzNPCnJSU1ZtSEdJZnBPUWFkcnFRR1F3TlEwL0g4OXZrSG15U2YwWDhJV1ZzRGhyRnpaWEFya0NGN0hQa2ZBNEgzaHoKQU1vQnE1d0twcWRPNkJTbFBHYitkQVdTZTgwcG1Ma3pCMzhTR1FPWHFiS2FLT2tzVXF0cFc1YkpOWWtYdXhUVgp1cml1bXBaRVN2aFM3TW9lWmxIMWJFK3lGUEVJVTFsQ055WE1iZXhCcW8xTXVHdXdybnFCdXU0MC8rV0l3ekNVCldlcDIwbkNXeEgrMWdtbW0xcS93SmpQS2RScDhHNnhBZm1MUWZ6SjZwUVFMazdkblFQZFBEc3h6OUZITWZONjYKN2pobHZ4eHBYckJYVUNLZUUrT2xVTVBIbmoxRW1OTDZ6cng3a01tb2VpQWE3eWxHUUVoMjNyM1Q5WmtKNzNkegpGN1BJVExESXRvNFBRZElEN3J0WFhQeHdWczF3QmhSUGNtbUQvTGQwSG5SNnFKclhMNVNDUFBNeVUyeDc1cnlqCkZJeGN5cWVlK0phQzNEMUZtdDRqYkJBRURuQWZmTWowTjBOUXA4NEVHUXpoSG1wR0Y0T0xrODVmRk0wMXpVcy8KMkZobDJ6TE1sVksySWdQcVYxdXc0MWJQdmtWVnhSUnFuRnhKZEhJYnJCVm9KZkNUaDlEYm83Z2RKeW04WWx2Lwoxb0JDWkJhTlUvSXh1eElqaGJWTEVHVTlnZk1ENDRndVJKbS80ZXI0VnRiS0FrMS9vSnNDWUtOeFh1UW5hT3hQCjhPWG9lMGx3WmpTdjgySFd6VjBCbjZkc3d3SURBUUFCTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElDQVFBVWVxa08KNVd1SHJtWnBmZm15ekhPY1pGUzluTVpiWFFHc2RmR3owWW9NSTVaWlFBTTFSRFZTRDBQVTJab3VuL0xhNWNMMQpsbTdFdGo1bUdEQ0tLZEN5ZHpUZHo1YkR2b1VFUTdnTGtkdHpuL2FQQllrQWRUUWxlVVhDai8rVWRIWkRLSGdnCm9ueEZNMXJWOW5jejJUeVppd21DVDN1aHk4MzQ3RnRkaDNoZkhVS0pKTUdNVTdFVnhHVlJJVEtyTVoyeGdVakIKUmtZenUvc3RCVXlNTVBlWXA3YWNCQUFieXFJbklRRkdXY0RHYTAwVHR6QTJOc09nMWdEUEZGMzMzL3FHUkFzNQo1d253OWxUbXA1cDNPS1R6ZDBub0ZuT29CQ1Z4bE1zMVNSOUJQazlPdFFnSjBUbXVVL0FlUTBOemQ0bDA1M2sxCmN6dHVWQVB2WjZBRzdZUTF6U1F1TU9yaUxDMkRHaUxNbmhwRlRFWFRVYzA5eVlWYmYweS92a01ocEh0YkhOOCsKS1cwbVo0VEw2R3lYR09xSkJUK21ocCs0THV4MVR0VGpjVWxROVZpYVJrWXArbVR5bUtsajJiL2pSTjRqWlNTYwovbys4TGZtWEt2VDlPalpGU2xIZzhLRHJMbkRCSDF1dXlmSWhERW54dU5WcjJzeHhXWEpSc1RJSUhleVhjSTdQCjlacUhraExZYXpvQjE1RHlwVnpnZ3c1L0U3LzNWQWxTNFRDSUVhbi94OFlWN2dSSm41OFBEZk9CWktsNWJxNGkKYWpBVGpnRVM5NTRFUGY5UlJxcEFJQTFaK0lDR3hITlBrVFFxSWt2bWdjRVl5YVJBQUpERDZWbUtSQkFhdUM1NwpRdWdmUERoSTJSN3c2Mm5PTlY0NG5DdUJ0czhNSGVGNTBxWmx0QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions:
      - v1beta1
    timeoutSeconds: 3
