version: '3.7'

services:
    gateway:
        depends_on:
            - minio
        ports:
            - 8080:80
        build: ../..
        command: dist/gateway.js
        env_file: .env
        environment:
            PORT: 80

    registry:
        depends_on:
            - minio
        ports:
            - 8090:80
        build: ../..
        command: dist/registry.js
        env_file: .env
        environment:
            PORT: 80

    minio:
        image: minio/minio
        ports:
            - 9000:9000
        command: server /var/minio
        environment:
            MINIO_ACCESS_KEY: $AWS_ACCESS_KEY_ID
            MINIO_SECRET_KEY: $AWS_SECRET_ACCESS_KEY
        volumes:
            - './minio_mount:/var/minio:rw'
