version: "3.7"

services:
  graphql-gateway.schema-registry:
    build:
      args:
        target: DEBUG
    command:
      - yarn
      - debug
    volumes:
      - ./schema-registry/src:/service/src
    environment:
      - NODE_ENV=dev
    ports:
      - 4001:81
      - 58581:5858
