version: "3.7"

services:
  graphql-gateway.graphql-server:
    build:
      context: ./graphql-server
    depends_on:
      - graphql-gateway.schema-registry
    healthcheck:
      disable: true
    ports:
      - 3000:8011
  graphql-gateway.schema-registry:
    build:
      context: ./schema-registry
      args:
        target: PRODUCTION
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/isAlive"]
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      - PORT=80
      - GRPC_PORT=81
    ports:
      - 4000:80
      - 4001:81
