version: "3.7"

services:
  graphql-gateway.schema-registry:
    build:
      context: ./schema-registry
      args:
        target: PRODUCTION
    healthcheck:
      disable: true
    environment:
      - PORT=80
      - NODE_ENV=dev
    ports:
      - 4001:80
