version: "3.7"

services:
  graphql-gateway.schema-registry:
    build:
      args:
        target: DEBUG
    command:
      - yarn
      - debug
    volumes:
      - ./schema-registry:/service
      - /service/node_modules
    ports:
      - 58581:5858
