version: "3.7"

services:
  agogos.graphql-server:
    build:
      context: ./services/graphql-server
    depends_on:
      - agogos.registry
    healthcheck:
      disable: true
    ports:
      - 8011:8011

  agogos.registry:
    build:
      context: ./services/registry
      args:
        target: PRODUCTION
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      - PORT=80
      - GRPC_PORT=81
    ports:
      - 8012:80
      - 8013:81

  oidc-server-mock:
    container_name: oidc-server-mock
    image: soluto/oidc-server-mock
    ports:
      - "5011:80"
    environment:
      - CLIENT_CREDENTIALS_CLIENT_ID=client-credentials-mock-client
      - CLIENT_CREDENTIALS_CLIENT_SECRET=client-credentials-mock-client-secret
      - API_RESOURCE=some-app
