version: "3.7"

services:
  graphql-gateway.graphql-server:
    build:
      context: ./graphql-server
    healthcheck:
      disable: true
    ports:
      - 3000:8011
  graphql-gateway.schema-registry:
    build:
      context: ./schema-registry
      args:
        target: PRODUCTION
    healthcheck:
      disable: true
    environment:
      - PORT=80
      - GRPC_PORT=81
      - NODE_ENV=dev
    ports:
      - 4000:80
      - 4001:81
