version: "3.7"

services:
  graphql-gateway.resource-controller:
    build: 
      context: ./app/resource-controller
      args: 
        target: PRODUCTION
    healthcheck:
      disable: true
    environment:
      - PORT=80
      - NODE_ENV=dev
    ports:
      - 4001:80