version: "3.7"

services:
  gateway:
    container_name: gateway
    build:
      dockerfile: Debug.Dockerfile
      context: services/graphql-server
    depends_on:
      - registry
      - customer-api
      - hotel-api
      - order-api
    ports:
      - "8011:8011"
      - "40000:40000"
    security_opt:
      - "seccomp:unconfined"
    environment:
      LOG_LEVEL: DEBUG
      REGISTRY_URL: registry:81

  registry:
    container_name: registry
    build:
      args:
        target: DEBUG
      context: services/registry
    depends_on:
      - resources
    ports:
      - "8080:80"
      - "8081:81"
    environment:
      LOG_LEVEL: INFO
      PORT: 80
      GRPC_PORT: 81

      REMOTESOURCE__FILESYSTEM: http://resources:3000

  resources:
    container_name: resources
    build: remote-sources/filesystem
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      SOURCE_FOLDER: /resources
    volumes:
      - ./remote-sources/filesystem/resources:/resources

  # Mock services
  customer-api:
    container_name: customer-api
    build: e2e/mocks/customer-api
    environment:
      - PORT=3000
    ports:
      - "8101:3000"

  hotel-api:
    container_name: hotel-api
    build: e2e/mocks/hotel-api
    environment:
      - PORT=3000
    ports:
      - "8102:3000"

  order-api:
    container_name: order-api
    build: e2e/mocks/order-api
    environment:
      - PORT=3000
    ports:
      - "8103:3000"
