version: "3.7"

services:
  graphql-gateway.resource-controller:
    build:
      args:
        target: DEBUG
    command:
      - yarn
      - debug
    volumes:
      - ./resource-controller:/service
      - /service/node_modules
    ports:
      - 58581:5858
