version: '3.7'

services:
    registry:
        build: services/registry
        ports:
            - '8080:80'
            - '8081:81'
        environment:
            PORT: 80
            GRPC_PORT: 81
            REMOTESOURCE__FILESYSTEM: http://resources:3000

    gateway:
        build: services/graphql-server
        ports:
            - '8011:8011'
        environment:
            REGISTRY_URL: registry:81

    resources:
        build: remote-sources/filesystem
        ports:
            - '3000:3000'
        environment:
            PORT: 3000
            SOURCE_FOLDER: /resources
        volumes:
            - ./remote-sources/filesystem/resources:/resources
