version: "3.7"

services:
  graphql-gateway.schema-registry:
    build:
      args:
        target: DEBUG
    command:
      - yarn
      - debug
    volumes:
      - ./schema-registry/src:/service/src
      - ./schema-registry/node_modules:/service/node_modules
    ports:
      - 58581:5858
