version: '3.7'

services:
    gateway:
        build: services/graphql-server
        depends_on:
            - registry
        ports:
            - '8000:8000'
        environment:
            PORT: 8000
            LOG_LEVEL: DEBUG
            REGISTRY_URL: registry:8002

    registry:
        build:
            context: services/registry
            args:
                target: DEBUG

        depends_on:
            - k8s-fs-resources
        environment:
            LOG_LEVEL: INFO
            PORT: 8001
            GRPC_PORT: 8002

            REMOTESOURCE__KUBERNETES_FS: http://k8s-fs-resources:8003

    k8s-fs-resources:
        build: remote-sources/kubernetes-fs
        environment:
            PORT: 8003
            RESOURCE_FOLDER: /resources
        volumes:
            - ./remote-sources/kubernetes-fs/resources:/resources

    # Mock services
    customer-api:
        container_name: customer-api
        build: e2e/mocks/customer-api
        environment:
            PORT: 3000

    hotel-api:
        container_name: hotel-api
        build: e2e/mocks/hotel-api
        environment:
            PORT: 3000

    order-api:
        container_name: order-api
        build: e2e/mocks/order-api
        environment:
            PORT: 3000
