version: 2.1

jobs:
  build_registry:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout

      - run:
          name: Build agogos-registry image
          command: docker build -t soluto/agogos-registry --build-arg target=PRODUCTION ./services/registry

  build_graphql_server:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout

      - run:
          name: Build agogos-graphql-server image
          command: docker build -t soluto/agogos-graphql-server --build-arg target=PRODUCTION ./services/graphql-server

  run_e2e_tests:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout

      - run:
          name: Build e2e tests image
          command: docker build -t soluto/agogos-e2e ./e2e

      - run:
          name: Run E2E tests
          working_directory: e2e
          command: scripts/run_tests.sh

workflows:
  version: 2

  build_all:
    jobs:
      - build_registry
      - build_graphql_server
      - run_e2e_tests:
          requires:
            - build_registry
            - build_graphql_server