version: 2.1
orbs:
  docker: circleci/docker@1.5.0

executors:
  linux:
    machine:
      image: ubuntu-2004:202010-01
jobs:
  create_docker_tag:
    executor: linux
    steps:
      - checkout
      - docker/check:
          docker-username: DOCKERHUB_USERNAME
          docker-password: DOCKERHUB_PASSWORD
      - docker/build:
          images: soluto/stitch
          path: ./services
          dockerfile: deployment/docker/Dockerfile
          tag: '$CIRCLE_TAG'
      - docker/push:
          image: soluto/stitch
          tag: '$CIRCLE_TAG,latest'

workflows:
  version: 2
  release_tag:
    jobs:
      - create_docker_tag:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
