version: 2.1
orbs:
    docker: circleci/docker@0.5.20
    node: circleci/node@1.1.6
executors:
    linux:
        machine:
            image: ubuntu-1604:201903-01
jobs:
    create_docker_tag:
        executor: linux
        steps:
            - checkout
            - docker/check:
                  docker-username: DOCKERHUB_USERNAME
                  docker-password: DOCKERHUB_PASSWORD
            - docker/pull:
                  images: 'soluto/stitch:$CIRCLE_SHA1'
            - run:
                  command: 'docker tag soluto/stitch:$CIRCLE_SHA1 soluto/stitch:$CIRCLE_TAG'
            - docker/push:
                  image: soluto/stitch
                  tag: '$CIRCLE_TAG'
    build_test:
        executor: linux
        steps:
            - checkout
            - node/install:
                  install-yarn: false
            - run:
                  command: |
                      cd services
                      npm ci
                      npm run test:full

workflows:
    version: 2
    pull_request:
        jobs:
            - build_test:
                  filters:
                      branches:
                          ignore:
                              - master
    master:
        jobs:
            - docker/publish:
                  executor: linux
                  deploy: true
                  docker-username: DOCKERHUB_USERNAME
                  docker-password: DOCKERHUB_PASSWORD
                  image: soluto/stitch
                  path: ./services
                  dockerfile: deployment/docker/Dockerfile
                  tag: '$CIRCLE_SHA1,latest'
                  filters:
                      branches:
                          only:
                              - master
    release_tag:
        jobs:
            - create_docker_tag:
                  filters:
                      tags:
                          only: /^v.*/
                      branches:
                          ignore: /.*/
