version: "2.4"

services:
  schema-registration:
    image: byrnedo/alpine-curl
    volumes:
      - .:/data
    command: -X POST --header "Content-Type:text/plain" -d @/data/schema.gql http://graphql-gateway.registry/schema/jsonplaceholder
    depends_on:
      graphql-gateway.registry:
        condition: service_healthy
