apiVersion: agogos.app/v1
kind: Schema
metadata:
  name: order-api
  namespace: user-namespace
spec:
  definition: |
    type Order {
      id: ID!
      customerId: ID!
      customer: Customer
        @rest(url: "http://customer-api.user-namespace/customer/{source.customerId}")
      hotelId: ID!
      hotel: Hotel
        @gql(url: "http://hotel-api.user-namespace/graphql", queryName: "hotel", arguments: "id:\"{source.hotelId}\"")
      startDate: String!
      endDate: String!
      adults: Int!
      children: Int
      city: String!
      country: String!
    }

    type Customer {
      orders: [Order]
        @rest(url: "http://order-api.user-namespace/customerOrders/{source.id}")
    }

    type Hotel {
      orders: [Order]
        @rest(url: "http://order-api.user-namespace/hotelOrders/{source.id}")
    }
