apiVersion: agogos.app/v1
kind: Upstream
metadata:
  name: order-api-upstream
  namespace: user-namespace
spec:
  host: "order-api.user-namespace"
  headers:
  - name: "X-API-CLIENT"
    value: agogos
  auth:
    authType: oauth2/client_credentials
    authority: "http://oidc-server-mock.oidc-namespace/connect/token"
    scope: order-api-scope