apiVersion: agogos.app/v1
kind: Schema
metadata:
  name: order-api
  namespace: user-namespace
spec:
  definition: |
    type Order {
      id: ID!
      customer: Customer
        @http(url: "http://customer-api.user-namespace/customer/:customerId")
      hotel: Hotel
        @gql(url: "http://hotel-api.user-namespace", queryName: "hotel", args: ["id"])
      startDate: String!
      endDate: String!
      adults: Int!
      children: Int
      city: String!
      country: String!
    }

    type Customer {
      orders: [Order]
        @http(url: "http://order-api.user-namespace/customerOrders/:customerId")
    }

    type Hotel {
      orders: [Order]
        @http(url: "http://order-api.user-namespace/hotelOrders/:hotelId")
    }
