version: '3.7'

services:
    gateway:
        image: local.dev/stitch
        depends_on:
            - minio
        ports:
            - 8080:80
        command: npm run start:gateway:watch
        env_file: .env
        environment:
            PORT: 80

    registry:
        image: local.dev/stitch
        depends_on:
            - minio
        ports:
            - 8090:80
        command: npm run start:registry:watch
        env_file: .env
        environment:
            PORT: 80

    minio:
        image: minio/minio
        ports:
            - 9000:9000
        command: server /var/minio
        env_file: .env
        environment:
            MINIO_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
            MINIO_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
        volumes:
            - './minio_mount:/var/minio:rw'
