apiVersion: agogos.soluto.com/v1
kind: GqlAuthProvider
metadata:
    name: user-service-auth provider
spec:
  type: oauth2/client_credentials
  authority: "http://oidc-server-mock"
  client_id: agogos_client_id
  client_secret:
    valueFrom:
    secretKeyRef:
      secretName: auth-secret
      key: client_secret