apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gqlschemas.graphql.gateway
spec:
  group: graphql.gateway
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: gqlschemas
    singular: gqlschema
    kind: GqlSchema
    shortNames:
    - gqls
    - gql
  additionalPrinterColumns:
    - name: Gql
      type: string
      description: The Gql schema
      JSONPath: .spec.gql
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            gql:
              type: string
  subresources:
    status: {}
