---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-api
  namespace: user-namespace
spec:
  selector:
    matchLabels:
      app: customer-api
  template:
    metadata:
      labels:
        app: customer-api
    spec:
      containers:
      - name: customer-api
        image: soluto/agogos-e2e-customer-api
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 30
      - name: airbag
        image: alex4soluto/airbag
        volumeMounts:
          - name: data
            mountPath: /app/data/airbag-config.json
            subPath: airbag-config.json
            readOnly: true
      volumes:
        - name: data
          configMap:
            name: customer-api
---
kind: Service
apiVersion: v1
metadata:
  name: customer-api
  namespace: user-namespace
spec:
  selector:
    app: customer-api
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-api
  namespace: user-namespace
data:
  airbag-config.json: |
        {
          "backend": "http://localhost:3000",
          "JWTProviders": [
              {
                  "iss": "http://oidc-server-mock.oidc-namespace",
                  "aud": "customer-api-scope"
              }
            ],
            "UnauthenticatedPaths": [
                "/health"
            ]
        }
---
