---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: clue/json-server
        volumeMounts:
          - name: data
            mountPath: data
        command:
          - json-server
          - --port
          - "80"
          - server.json
      volumes:
        - name: data
          configMap:
            name: user-service
---
kind: Service
apiVersion: v1
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service
data:
  server.json: |
        {
          "users": [{ "id": "1", "firstName": "john", "lastName": "doe" }]
        }
---
