---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: user-namespace
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: clue/json-server
        volumeMounts:
          - name: data
            mountPath: data
            readOnly: true
        command:
          - json-server
          - --port
          - "8080"
          - server.json
        livenessProbe:
          httpGet:
            path: /users
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 30
      - name: airbag
        image: alex4soluto/airbag
        volumeMounts:
          - name: data
            mountPath: /app/data/airbag-config.json
            subPath: airbag-config.json
            readOnly: true
      volumes:
        - name: data
          configMap:
            name: user-service
---
kind: Service
apiVersion: v1
metadata:
  name: user-service
  namespace: user-namespace
spec:
  selector:
    app: user-service
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service
  namespace: user-namespace
data:
  server.json: |
        {
          "users": [{ "id": "1", "firstName": "john", "lastName": "doe" }]
        }
  airbag-config.json: |
        {
          "backend": "http://localhost:8080",
          "JWTProviders": [
              {
                  "iss": "http://oidc-server-mock.oidc-namespace",
                  "aud": "user-service-scope"
              }
            ],
            "UnauthenticatedPaths": [
                "/health"
            ]
        }
---
