apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: schemas.agogos.app
spec:
  group: agogos.app
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: schemas
    singular: schema
    kind: Schema
    shortNames:
    - gqls
    - gql
  additionalPrinterColumns:
    - name: Gql
      type: string
      description: The Gql schema
      JSONPath: .spec.definition
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            definition:
              type: string
  subresources:
    status: {}
