---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-api
  namespace: user-namespace
spec:
  selector:
    matchLabels:
      app: hotel-api
  template:
    metadata:
      labels:
        app: hotel-api
    spec:
      containers:
        - name: hotel-api
          image: soluto/agogos-e2e-hotel-api
          imagePullPolicy: Never
          command:
            - yarn
            - start
          livenessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 3
            periodSeconds: 30
        - name: airbag
          image: alex4soluto/airbag
          volumeMounts:
            - name: data
              mountPath: /app/data/airbag-config.json
              subPath: airbag-config.json
              readOnly: true
      volumes:
        - name: data
          configMap:
            name: hotel-api
---
kind: Service
apiVersion: v1
metadata:
  name: hotel-api
  namespace: user-namespace
spec:
  selector:
    app: hotel-api
  ports:
    - name: http
      port: 80
      targetPort: 4000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hotel-api
  namespace: user-namespace
data:
  airbag-config.json: |
    {
      "backend": "http://localhost:3000",
      "JWTProviders": [
          {
              "iss": "http://oidc-server-mock.oidc-namespace",
              "aud": "hotel-api-scope"
          }
        ],
        "UnauthenticatedPaths": [
            "/health"
        ]
    }
---

