apiVersion: agogos.app/v1
kind: Schema
metadata:
    name: order-api
spec:
    definition: |
        type Order {
            id: ID!
            customer: Customer!
                @http(url: "http://localhost:8101/customer/:customerId")
            hotel: Hotel!
                @gql(url: "http://localhost:8102/graphql", queryName: "hotel", arguments: "id:\"{source.hotelId}\"")
            startDate: String!
            endDate: String!
            adults: Int!
            children: Int
            city: String!
            country: String!
        }

        type Customer {
            orders: [Order!] @http(url: "http://localhost:8103/customerOrders/:id")
        }

        type Hotel {
            orders: [Order!] @http(url: "http://localhost:8103/hotelOrders/:id")
        }
