name: Main

on:
  push:
    paths-ignore:
      - README.md
      - docs

jobs:
  test_js:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - run: npm ci
        working-directory: services

      - run: npm run test:full
        working-directory: services
