apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
  - image: graphql-gateway
    context: ../../services/graphql-server
    docker:
      dockerfile: dockerfile
  - image: schema-registry
    context: ../../services/schema-registry
    docker:
      dockerfile: dockerfile
  - image: gql-controller
    context: ../../remote-sources/kubernetes
    docker:
      dockerfile: dockerfile
deploy:
  kubectl:
    manifests:
    - ./deployments/infra/rbac.yaml

    - ./deployments/infra/admission-tls-secret.yaml
    - ./deployments/infra/schema-registry.yaml
    - ./deployments/infra/gql-controller.yaml
    - ./deployments/infra/gateway.yaml

    - ./deployments/infra/webhook.yaml

    - ./deployments/services/user-service.yaml
    - ./deployments/services/user-subscription-service.yaml

    - ./deployments/schemas/user-service.gql.yaml
    - ./deployments/schemas/user-subscription-service.gql.yaml
